version: "3.9"

services:
  news-alerts-discord:
    image: node:lts
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DISCORD_CHANNEL_ID=123456789
      - DISCORD_BOT_AUTHORIZATION=xxx.yyy.zzz
    command: bash docker-command.sh
